// Mock data for Diplomat South Africa
import { Company, User, Customer, Product, Budget, Promotion, TradingTerms } from '../types';

export const diplomatCompany: Company = {
  id: 'DIPL-SA-001',
  code: 'DIPLOMAT-SA',
  name: 'Diplomat South Africa',
  logo: '/diplomat-logo.png',
  industry: 'FMCG - Confectionery & Snacks',
  country: 'South Africa',
  currency: 'ZAR',
  fiscalYearStart: '2024-03-01',
  fiscalYearEnd: '2025-02-28',
  settings: {
    theme: 'light',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: 'en-ZA',
  },
  createdAt: '2023-01-15T00:00:00Z',
  updatedAt: '2024-01-15T00:00:00Z',
};

export const mockUsers: User[] = [
  {
    id: 'usr-001',
    email: 'john.smith@diplomat.co.za',
    name: 'John Smith',
    role: 'sales_director',
    companyId: 'DIPL-SA-001',
    companyCode: 'DIPLOMAT-SA',
    department: 'Sales',
    region: 'National',
    permissions: ['view_all', 'edit_all', 'approve_budgets', 'manage_users'],
    avatar: 'https://ui-avatars.com/api/?name=John+Smith&background=0D9488&color=fff',
    createdAt: '2023-01-15T00:00:00Z',
    lastLogin: '2024-08-24T08:30:00Z',
  },
  {
    id: 'usr-002',
    email: 'sarah.johnson@diplomat.co.za',
    name: 'Sarah Johnson',
    role: 'kam',
    companyId: 'DIPL-SA-001',
    companyCode: 'DIPLOMAT-SA',
    department: 'Sales',
    region: 'Gauteng',
    permissions: ['view_own', 'edit_own', 'create_promotions'],
    avatar: 'https://ui-avatars.com/api/?name=Sarah+Johnson&background=7C3AED&color=fff',
    createdAt: '2023-02-01T00:00:00Z',
    lastLogin: '2024-08-24T09:15:00Z',
  },
  {
    id: 'usr-003',
    email: 'michael.ndlovu@diplomat.co.za',
    name: 'Michael Ndlovu',
    role: 'regional_manager',
    companyId: 'DIPL-SA-001',
    companyCode: 'DIPLOMAT-SA',
    department: 'Sales',
    region: 'Western Cape',
    permissions: ['view_region', 'edit_region', 'approve_promotions'],
    avatar: 'https://ui-avatars.com/api/?name=Michael+Ndlovu&background=DC2626&color=fff',
    createdAt: '2023-03-10T00:00:00Z',
    lastLogin: '2024-08-24T07:45:00Z',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    code: 'SHOPRITE-001',
    name: 'Shoprite Holdings',
    type: 'retail_chain',
    segment: 'Modern Trade',
    region: 'National',
    creditLimit: 5000000,
    paymentTerms: 30,
    status: 'active',
    hierarchy: {
      group: 'Shoprite Group',
      banner: 'Shoprite',
      region: 'National',
      stores: 450,
    },
    contacts: [
      {
        name: 'Peter van der Merwe',
        role: 'Category Manager - Confectionery',
        email: 'peter.vdm@shoprite.co.za',
        phone: '+27 21 980 4000',
      },
    ],
    tradingTerms: {
      listingFee: 2.5,
      promotionalDiscount: 15,
      settlementDiscount: 2,
      rebate: 3.5,
    },
  },
  {
    id: 'cust-002',
    code: 'PICKNPAY-001',
    name: 'Pick n Pay Stores',
    type: 'retail_chain',
    segment: 'Modern Trade',
    region: 'National',
    creditLimit: 4500000,
    paymentTerms: 30,
    status: 'active',
    hierarchy: {
      group: 'Pick n Pay Group',
      banner: 'Pick n Pay',
      region: 'National',
      stores: 320,
    },
    contacts: [
      {
        name: 'Linda Mthembu',
        role: 'Buying Manager - Snacks',
        email: 'linda.mthembu@pnp.co.za',
        phone: '+27 21 658 1000',
      },
    ],
    tradingTerms: {
      listingFee: 2.0,
      promotionalDiscount: 12,
      settlementDiscount: 2.5,
      rebate: 3.0,
    },
  },
  {
    id: 'cust-003',
    code: 'SPAR-001',
    name: 'SPAR Group',
    type: 'retail_chain',
    segment: 'Modern Trade',
    region: 'National',
    creditLimit: 3500000,
    paymentTerms: 45,
    status: 'active',
    hierarchy: {
      group: 'SPAR South Africa',
      banner: 'SPAR',
      region: 'National',
      stores: 280,
    },
    contacts: [
      {
        name: 'Johan Kruger',
        role: 'National Buyer - Confectionery',
        email: 'johan.kruger@spar.co.za',
        phone: '+27 31 719 1900',
      },
    ],
    tradingTerms: {
      listingFee: 1.5,
      promotionalDiscount: 10,
      settlementDiscount: 3,
      rebate: 2.5,
    },
  },
  {
    id: 'cust-004',
    code: 'WOOLWORTHS-001',
    name: 'Woolworths Food',
    type: 'retail_chain',
    segment: 'Premium Trade',
    region: 'National',
    creditLimit: 2500000,
    paymentTerms: 60,
    status: 'active',
    hierarchy: {
      group: 'Woolworths Holdings',
      banner: 'Woolworths Food',
      region: 'National',
      stores: 180,
    },
    contacts: [
      {
        name: 'Amanda Chen',
        role: 'Senior Buyer - Premium Snacks',
        email: 'amanda.chen@woolworths.co.za',
        phone: '+27 21 407 9111',
      },
    ],
    tradingTerms: {
      listingFee: 3.0,
      promotionalDiscount: 8,
      settlementDiscount: 1.5,
      rebate: 2.0,
    },
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    sku: 'DIP-CHO-001',
    name: 'Diplomat Milk Chocolate 100g',
    category: 'Chocolate',
    brand: 'Diplomat',
    vendor: 'Diplomat SA',
    unitPrice: 24.99,
    caseSize: 24,
    barcode: '6001234567890',
    status: 'active',
    hierarchy: {
      category: 'Confectionery',
      subCategory: 'Chocolate',
      brand: 'Diplomat',
      variant: 'Milk Chocolate',
      size: '100g',
    },
    margins: {
      cost: 12.50,
      wholesalePrice: 18.75,
      retailPrice: 24.99,
      grossMargin: 33.3,
    },
  },
  {
    id: 'prod-002',
    sku: 'DIP-CHO-002',
    name: 'Diplomat Dark Chocolate 100g',
    category: 'Chocolate',
    brand: 'Diplomat',
    vendor: 'Diplomat SA',
    unitPrice: 29.99,
    caseSize: 24,
    barcode: '6001234567907',
    status: 'active',
    hierarchy: {
      category: 'Confectionery',
      subCategory: 'Chocolate',
      brand: 'Diplomat',
      variant: 'Dark Chocolate',
      size: '100g',
    },
    margins: {
      cost: 15.00,
      wholesalePrice: 22.50,
      retailPrice: 29.99,
      grossMargin: 33.3,
    },
  },
  {
    id: 'prod-003',
    sku: 'DIP-SNK-001',
    name: 'Diplomat Potato Chips - Original 125g',
    category: 'Snacks',
    brand: 'Diplomat Snacks',
    vendor: 'Diplomat SA',
    unitPrice: 19.99,
    caseSize: 20,
    barcode: '6001234567914',
    status: 'active',
    hierarchy: {
      category: 'Snacks',
      subCategory: 'Potato Chips',
      brand: 'Diplomat Snacks',
      variant: 'Original',
      size: '125g',
    },
    margins: {
      cost: 8.50,
      wholesalePrice: 14.00,
      retailPrice: 19.99,
      grossMargin: 42.5,
    },
  },
  {
    id: 'prod-004',
    sku: 'DIP-SNK-002',
    name: 'Diplomat Potato Chips - BBQ 125g',
    category: 'Snacks',
    brand: 'Diplomat Snacks',
    vendor: 'Diplomat SA',
    unitPrice: 19.99,
    caseSize: 20,
    barcode: '6001234567921',
    status: 'active',
    hierarchy: {
      category: 'Snacks',
      subCategory: 'Potato Chips',
      brand: 'Diplomat Snacks',
      variant: 'BBQ',
      size: '125g',
    },
    margins: {
      cost: 8.50,
      wholesalePrice: 14.00,
      retailPrice: 19.99,
      grossMargin: 42.5,
    },
  },
  {
    id: 'prod-005',
    sku: 'DIP-BIS-001',
    name: 'Diplomat Cream Biscuits 200g',
    category: 'Biscuits',
    brand: 'Diplomat',
    vendor: 'Diplomat SA',
    unitPrice: 14.99,
    caseSize: 24,
    barcode: '6001234567938',
    status: 'active',
    hierarchy: {
      category: 'Biscuits',
      subCategory: 'Cream Filled',
      brand: 'Diplomat',
      variant: 'Vanilla Cream',
      size: '200g',
    },
    margins: {
      cost: 6.00,
      wholesalePrice: 10.50,
      retailPrice: 14.99,
      grossMargin: 40.0,
    },
  },
];

export const mockBudgets: Budget[] = [
  {
    id: 'budget-001',
    name: 'FY2024 National Sales Budget',
    fiscalYear: '2024',
    totalAmount: 25000000,
    allocatedAmount: 18500000,
    spentAmount: 12350000,
    status: 'active',
    type: 'annual',
    breakdown: {
      marketing: 7500000,
      tradeTerms: 10000000,
      promotions: 5000000,
      coOp: 2500000,
    },
    scenarios: [
      {
        name: 'Conservative',
        totalAmount: 22000000,
        growth: 5,
      },
      {
        name: 'Balanced',
        totalAmount: 25000000,
        growth: 12,
      },
      {
        name: 'Aggressive',
        totalAmount: 30000000,
        growth: 25,
      },
    ],
  },
  {
    id: 'budget-002',
    name: 'Q3 2024 Promotional Budget',
    fiscalYear: '2024',
    totalAmount: 3500000,
    allocatedAmount: 2800000,
    spentAmount: 1950000,
    status: 'active',
    type: 'quarterly',
    breakdown: {
      inStore: 1500000,
      digital: 500000,
      leaflet: 1000000,
      sampling: 500000,
    },
  },
];

export const mockPromotions: Promotion[] = [
  {
    id: 'promo-001',
    name: 'Spring Chocolate Festival',
    type: 'price_reduction',
    status: 'active',
    startDate: '2024-09-01',
    endDate: '2024-09-30',
    customer: 'Shoprite Holdings',
    products: ['Diplomat Milk Chocolate 100g', 'Diplomat Dark Chocolate 100g'],
    mechanics: {
      discountType: 'percentage',
      discountValue: 25,
      buyQuantity: 2,
      getQuantity: 0,
    },
    budget: 450000,
    actualSpend: 0,
    expectedUplift: 180,
    actualUplift: 0,
    roi: 0,
    aiRecommendations: {
      optimalPrice: 18.74,
      expectedUplift: 220,
      confidenceScore: 0.85,
      cannibalizationRisk: 'low',
      conflictingPromotions: [],
    },
  },
  {
    id: 'promo-002',
    name: 'Back to School Snack Pack',
    type: 'bundle',
    status: 'planned',
    startDate: '2025-01-15',
    endDate: '2025-02-15',
    customer: 'Pick n Pay Stores',
    products: ['Diplomat Potato Chips - Original 125g', 'Diplomat Potato Chips - BBQ 125g', 'Diplomat Cream Biscuits 200g'],
    mechanics: {
      bundlePrice: 49.99,
      originalPrice: 54.97,
      savingsAmount: 4.98,
    },
    budget: 320000,
    actualSpend: 0,
    expectedUplift: 150,
    actualUplift: 0,
    roi: 0,
    aiRecommendations: {
      optimalPrice: 44.99,
      expectedUplift: 195,
      confidenceScore: 0.78,
      cannibalizationRisk: 'medium',
      conflictingPromotions: ['promo-003'],
    },
  },
  {
    id: 'promo-003',
    name: 'Weekend Special - Chips',
    type: 'bogo',
    status: 'completed',
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    customer: 'SPAR Group',
    products: ['Diplomat Potato Chips - Original 125g', 'Diplomat Potato Chips - BBQ 125g'],
    mechanics: {
      discountType: 'bogo',
      buyQuantity: 1,
      getQuantity: 1,
      getDiscount: 50,
    },
    budget: 280000,
    actualSpend: 275000,
    expectedUplift: 200,
    actualUplift: 235,
    roi: 2.8,
    postPromoAnalysis: {
      sustainedUplift: 15,
      pantryLoading: 35,
      newBuyers: 12,
      repeatRate: 68,
    },
  },
];

export const mockDashboardMetrics = {
  totalSales: {
    value: 45678900,
    change: 12.5,
    period: 'YTD',
    target: 50000000,
  },
  marketShare: {
    value: 18.5,
    change: 2.3,
    period: 'Current',
    category: 'Confectionery',
  },
  promotionalROI: {
    value: 3.2,
    change: 0.5,
    period: 'Last Quarter',
    benchmark: 2.5,
  },
  budgetUtilization: {
    value: 74,
    allocated: 18500000,
    spent: 13690000,
    remaining: 4810000,
  },
  customerPerformance: [
    { name: 'Shoprite', sales: 12500000, growth: 15 },
    { name: 'Pick n Pay', sales: 10200000, growth: 8 },
    { name: 'SPAR', sales: 8900000, growth: 12 },
    { name: 'Woolworths', sales: 6500000, growth: 22 },
    { name: 'Others', sales: 7578900, growth: 5 },
  ],
  productPerformance: [
    { name: 'Chocolate', sales: 18500000, units: 740000, growth: 18 },
    { name: 'Snacks', sales: 15200000, units: 760000, growth: 10 },
    { name: 'Biscuits', sales: 11978900, units: 798600, growth: 7 },
  ],
  monthlyTrend: [
    { month: 'Jan', sales: 3200000, budget: 3500000 },
    { month: 'Feb', sales: 3450000, budget: 3500000 },
    { month: 'Mar', sales: 3800000, budget: 3700000 },
    { month: 'Apr', sales: 3650000, budget: 3800000 },
    { month: 'May', sales: 3900000, budget: 3900000 },
    { month: 'Jun', sales: 4100000, budget: 4000000 },
    { month: 'Jul', sales: 4250000, budget: 4100000 },
    { month: 'Aug', sales: 4328900, budget: 4200000 },
  ],
  alerts: [
    {
      type: 'warning',
      title: 'Promotion Conflict Detected',
      message: 'Overlapping chocolate promotions at Shoprite and Pick n Pay may cannibalize sales',
      timestamp: '2024-08-24T10:30:00Z',
    },
    {
      type: 'success',
      title: 'Budget Milestone Achieved',
      message: 'Q3 promotional budget utilization reached 85% with positive ROI',
      timestamp: '2024-08-24T09:15:00Z',
    },
    {
      type: 'info',
      title: 'AI Insight Available',
      message: 'New pricing optimization suggests 15% uplift opportunity for SPAR promotions',
      timestamp: '2024-08-24T08:00:00Z',
    },
  ],
};

// Helper functions to get mock data
export const getMockCompany = () => diplomatCompany;
export const getMockUsers = () => mockUsers;
export const getMockCustomers = () => mockCustomers;
export const getMockProducts = () => mockProducts;
export const getMockBudgets = () => mockBudgets;
export const getMockPromotions = () => mockPromotions;
export const getMockDashboardMetrics = () => mockDashboardMetrics;

// Simulate API calls with delays
export const fetchWithDelay = <T>(data: T, delay: number = 500): Promise<T> => {
  return new Promise((resolve) => {
    setTimeout(() => resolve(data), delay);
  });
};